set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property PACKAGE_PIN E3 [get_ports clk_100MHz]
set_property PACKAGE_PIN C2 [get_ports reset_n]
set_property PACKAGE_PIN A11 [get_ports rx]
set_property PACKAGE_PIN B11 [get_ports tx]

set_property IOSTANDARD LVCMOS33 [get_ports {spi0_cs_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports spi0_miso]
set_property IOSTANDARD LVCMOS33 [get_ports spi0_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports spi0_sck]
set_property PACKAGE_PIN D3 [get_ports {spi0_cs_n[0]}]
set_property PACKAGE_PIN F4 [get_ports spi0_miso]
set_property PACKAGE_PIN D2 [get_ports spi0_mosi]
set_property PACKAGE_PIN H2 [get_ports spi0_sck]

set_property DRIVE 12 [get_ports tx]


set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[0]}]
set_property PACKAGE_PIN H5 [get_ports {gpio_rtl_0_tri_o[0]}]
set_property PACKAGE_PIN J5 [get_ports {gpio_rtl_0_tri_o[1]}]
set_property PACKAGE_PIN T9 [get_ports {gpio_rtl_0_tri_o[2]}]
set_property PACKAGE_PIN T10 [get_ports {gpio_rtl_0_tri_o[3]}]

set_property PULLTYPE PULLUP [get_ports spi0_miso]

set_property OFFCHIP_TERM NONE [get_ports spi0_mosi]
set_property OFFCHIP_TERM NONE [get_ports spi0_sck]
set_property OFFCHIP_TERM NONE [get_ports tx]
set_property OFFCHIP_TERM NONE [get_ports gpio_rtl_0_tri_o[3]]
set_property OFFCHIP_TERM NONE [get_ports gpio_rtl_0_tri_o[2]]
set_property OFFCHIP_TERM NONE [get_ports gpio_rtl_0_tri_o[1]]
set_property OFFCHIP_TERM NONE [get_ports gpio_rtl_0_tri_o[0]]
set_property OFFCHIP_TERM NONE [get_ports spi0_cs_n[0]]
